### ISSUE TITLE
Review Issues

### ISSUE THREAD

**Issue by jdecock** [DasOakster/hriderhaggard_allan-quatermain#1]
- [x] `se modernize-spelling` still makes several changes. As far as I can see they should all be accepted with the exception of changing "up-rising" to "uprising" in chapter-13.xhtml.
- [x] `se build-toc` needs to be run. It makes a couple of small changes to the table of contents.
- [x] chapter-4.xhtml: "que sais-je?" should have the question mark moved outside the `</i>`
- [x] chapter-7.xhtml: You can combine `<span xml:lang="zu"><em>` into `<em xml:lang="zu">` (and trim the trailing `</span>`)
- [x] Clean up local.css:
	- [x] The first two lines (@charset and @namespace) lines are included twice
	- [x] The poem styles that match up with the song/verse rules should be combined. This would result in something like:
	```
  [epub|type~="z3998:poem"] p + p{
	  margin-top: 1em;
  }
  
  [epub|type~="z3998:poem"] p,
  [epub|type~="z3998:song"] p,
  [epub|type~="z3998:verse"] p{
	  text-align: initial;
	  text-indent: 0;
  }
  
  [epub|type~="z3998:poem"] p > span,
  [epub|type~="z3998:song"] p > span,
  [epub|type~="z3998:verse"] p > span{
	  display: block;
	  padding-left: 1em;
	  text-indent: -1em;
  }
  
  [epub|type~="z3998:poem"] p > span + br,
  [epub|type~="z3998:song"] p > span + br,
  [epub|type~="z3998:verse"] p > span + br{
	  display: none;
  }
	```
	Honestly, I don't know how important this is but this is how the SEMOS specifies things.
- [x] content.opf metadata:
	- [x] "Soloman" should be "Solomon" in the long and short descriptions.
	- [x] In the long description, "Longmans Magazine" and "King Solomon's Mines" should be wrapped in `<i>` (`&lt;i&gt;` after it's been escaped) tags and "Mines" should be capitalized.
	- [x] The meta data for "author" includes two `property="role"` values. Unfortunately, the SE build tool won't accept this so the second value ("ann") should be changed to `property="se:role"`. You can see another example of this down in the meta data for producer.
	- [x] You should add the `se:name.person.full-name` value for the author: `<meta property="se:name.person.full-name" refines="#author">Henry Rider Haggard</meta>`

**Comment by DasOakster** [comment]
OK - changes made:

se modernize spelling - left 'after-life' in Chapter 9 as is-the meaning here is in the life of the little girl to come in the future rather than her life after death

**Comment by jdecock** [comment]
Fair enough. I hate to do this, but I did turn up just a few more things. Super minor and after that you should be all set.

- [x] chapter-18.xhtml: You still have a `"` that should be removed in `<span xml:lang="zu">Inkoos"</span>`.
- [x] `se typogrify` needs to be run once more. I swear I did that yesterday and things were good, but right now it still makes a few changes, all of which seem valid.
- [x] `se clean` one final time to fix indentation in local.css

**Comment by DasOakster** [comment]
No problem at all - getting the tiny details right is what adds a lot of value to the catalog I think.  Fingers crossed this is done now!
